delete from AlbumRoots;
delete from Albums
delete from Images
delete from ImageHaarMatrix
delete from ImageInformation
delete from ImageMetadata
delete from ImagePositions
delete from ImageComments
delete from ImageCopyright
delete from Tags
delete from TagsTree
delete from ImageTags
delete from ImageProperties
delete from Searches
delete from DownloadHistory
delete from Settings
delete from ImageHistory
delete from ImageRelations
delete from TagProperties
delete from ImageTagProperties